sudo: false
language: python

cache: pip

# Tox cannot install pythons, so we set 3.5 as default, use 3.4 already
# available in container and then include 3.6 in matrix.
python:
  - 3.4
  - 3.5

env:
  # NOTE: On Travis web page define private STASH_URL, STASH_TOKEN, STASH_SECRET.
  global:
    - STASH_BOX=$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER:$STASH_SECRET
  matrix:
    - TOXENV=py34-django18
    - TOXENV=py34-django19
    - TOXENV=py34-django110
    - TOXENV=py34-django111
    - TOXENV=py34-django20

    - TOXENV=py35-django18
    - TOXENV=py35-django19
    - TOXENV=py35-django110
    - TOXENV=py35-django111
    - TOXENV=py35-django20
    - TOXENV=py35-django21

matrix:
  include:
    # Django 2.2 requires SQLite 3.8.3+ which is not available on Ubuntu Trusty
    # which is the default Ubuntu version on Travis CI. Run all Django 2.2+
    # tests on Ubuntu Xenial instead.
    - python: 3.5
      env: TOXENV=py35-django22
      dist: xenial
    - python: 3.6
      env: TOXENV=py36-django22
      dist: xenial

    # Python 3.7 on Travis CI is only available on Ubuntu Xenial.
    - python: 3.7
      env: TOXENV=py37-django22
      dist: xenial
    - python: 3.7
      env: TOXENV=py37-django111
      dist: xenial
    - python: 3.7
      env: TOXENV=py37-django20
      dist: xenial
    - python: 3.7
      env: TOXENV=py37-django21
      dist: xenial

    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.4  # i.e. skip installing 3.5
      env: TOXENV=lint
    - python: 3.4
      env: TOXENV=coverage  # run it after tests to collect reports from other jobs

install:
  - pip install tox stasher

script:
  - if [[ $TOXENV =~ coverage ]] && [ -n "$STASH_SECRET" ]; then
    stash pull $STASH_BOX -wc $(TOXENV= tox -l | wc -l);
    fi
  - if [[ ! $TOXENV =~ coverage ]] || [ -n "$STASH_SECRET" ]; then
    tox;
    fi
  - if [[ $TOXENV =~ py ]] && [ -n "$STASH_SECRET" ]; then
    stash push $STASH_BOX $(ls .coverage.*);
    fi

after_success:
  - if [[ $TOXENV =~ coverage ]]; then
    pip install --quiet python-coveralls;
    coveralls --ignore-errors;
    fi
