sudo: false
language: python
cache: pip
python: 3.8
dist: xenial

env:
  # NOTE: On Travis web page define private STASH_URL, STASH_TOKEN, STASH_SECRET.
  global:
    - STASH_BOX=$TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER:$STASH_SECRET

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.6
      env: TOXENV=py36-django30

    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.7
      env: TOXENV=py37-django30

    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.8
      env: TOXENV=py38-django30

    - python: 3.8
      env: TOXENV=checks
    - python: 3.8
      env: TOXENV=coverage  # Runs after tests to collect reports from other jobs

install:
  - pip install tox stasher

script:
  - if [[ $TOXENV =~ coverage ]] && [ -n "$STASH_SECRET" ]; then
    stash pull $STASH_BOX -wc $(TOXENV= tox -l | wc -l);
    fi
  - if [[ ! $TOXENV =~ coverage ]] || [ -n "$STASH_SECRET" ]; then
    tox;
    fi
  - if [[ $TOXENV =~ py ]] && [ -n "$STASH_SECRET" ]; then
    stash push $STASH_BOX $(ls .coverage.*);
    fi

after_success:
  - if [[ $TOXENV =~ coverage ]]; then
    pip install --quiet python-coveralls;
    coveralls --ignore-errors;
    fi
