sudo: false
language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.4
      env: TOXENV=py34-django19
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - coveralls
